### ISSUE TITLE
KV watches 

### ISSUE THREAD

**Issue by hwinkel** [SeaBattle/SeaConfig#1]
Does seagull implement watching on KV changes of the watch APIs of  etcd or consul. or does it make a periodic poll?

**Comment by comtihon** [comment]
Hi,
if `{cache, #{enable => true, update_time => TimeMS}}` is specified - seagull will periodically ask backend for new values of keys, which were set/get previosly.

**Comment by hwinkel** [comment]
Hi @comtihon I have seen this setting, thats where the polling question comes from. As far i know etcd and consul also have a API for watches which calls at value change. For a larger scale deployment this might be interesting.

**Comment by comtihon** [comment]
Yes. They provide some kind of offset to queue changes since last call. But this is not implemented here.
